[package]
name = "src"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
crossterm = "0.24.0"
env_logger = "0.9.0"
log-panics = "2.0"
rodio = "0.15.0"